import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientProvider } from "@/core/context/client-context";
import { ThemeProvider } from "@/core/components/ui/theme-provider";
import { Toaster } from "sonner";
import { ReactScan } from "@/core/components/custom/react-scan";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.className} antialiased bg-background-200 overflow-x-hidden`} suppressHydrationWarning
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ClientProvider>
                        {children}
                        <Toaster />

                    </ClientProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
